{% set name = "phasefieldx" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CastillonMiguel/phasefieldx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e5e2326c12127f1eee5fbf1dcbdc2d32e81ae159f2651531e8cd855d33f73728

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - fenics-dolfinx
    - gmsh
    - mpi4py
    - numpy
    - pandas
    - pyvista

test:
  source_files:
    - pyproject.toml
    - test
  requires:
    - pip
    - pytest
    - fenics-dolfinx
    - gmsh
    - mpi4py
    - numpy
    - pandas
    - pyvista
    - setuptools 
    - wheel 
  commands:
    - python -m build
    - pytest -vs test
    - pip check

about:
  home: https://github.com/CastillonMiguel/phasefieldx
  summary: 'PhaseFieldX: An Open-Source Framework for Advanced Phase-Field Simulations'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://phasefieldx.readthedocs.io
  dev_url: https://github.com/CastillonMiguel/phasefieldx

extra:
  recipe-maintainers:
    - CastillonMiguel
