{% set name = "phasefieldx" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CastillonMiguel/phasefieldx/archive/v{{ version }}.tar.gz
  sha256: e18f215b44f5b18279743bd2535c648249fa6a83f2fe8286914a2a5e3b0551a1

build:
  number: 0
  noarch: python

  # openmpi oversubscribe env
  script_env:
    - OMPI_ALLOW_RUN_AS_ROOT=1
    - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - OMPI_MCA_rmaps_base_oversubscribe=1
    - OMPI_MCA_plm=isolated
    - OMPI_MCA_btl=vader,self
    - OMPI_MCA_btl_vader_single_copy_mechanism=none
    - MPIEXEC_TIMEOUT=400

  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - fenics-dolfinx
    - gmsh
    - mpi4py
    - numpy
    - pandas
    - pyvista


about:
  home: https://github.com/CastillonMiguel/phasefieldx
  summary: 'PhaseFieldX: An Open-Source Framework for Advanced Phase-Field Simulations'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://phasefieldx.readthedocs.io
  dev_url: https://github.com/CastillonMiguel/phasefieldx

extra:
  recipe-maintainers:
    - CastillonMiguel
