{% set name = "phasefieldx" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/phasefieldx-{{ version }}.tar.gz
  sha256: 91a33ca2ff3e5ec4c2e58ba48f45230a1c98660a90864db9053584826c02b5b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - fenics-dolfinx
    - gmsh
    - mpi4py
    - numpy
    - pandas
    - pyvista

test:
  imports:
    - phasefieldx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CastillonMiguel/phasefieldx
  summary: 'PhaseFieldX: An Open-Source Framework for Advanced Phase-Field Simulations'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://phasefieldx.readthedocs.io
  dev_url: https://github.com/CastillonMiguel/phasefieldx

extra:
  recipe-maintainers:
    - CastillonMiguel